version: "3.9"

services:
  database:
    image: postgres
    container_name: database_softmakers_api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=softmakers_database
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
